"""add signature verification

Revision ID: cac6059f8c48
Revises: fad99be49787
Create Date: 2026-08-27 15:17:58.993069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac6059f8c48'
down_revision: Union[str, Sequence[str], None] = 'fad99be49787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature_checks',
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.add_column('endpoints', sa.Column('signature_provider', sa.String(length=32), nullable=True))
    op.add_column('endpoints', sa.Column('signature_secret', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'signature_secret')
    op.drop_column('endpoints', 'signature_provider')
    op.drop_table('signature_checks')
    # ### end Alembic commands ###
