"""crea endpoints y requests

Revision ID: fad99be49787
Revises: 
Create Date: 2026-08-22 21:40:02.344874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fad99be49787'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingest_token', sa.String(length=64), nullable=False),
    sa.Column('view_token', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_expires_at'), 'endpoints', ['expires_at'], unique=False)
    op.create_index(op.f('ix_endpoints_ingest_token'), 'endpoints', ['ingest_token'], unique=True)
    op.create_index(op.f('ix_endpoints_owner_user_id'), 'endpoints', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_endpoints_view_token'), 'endpoints', ['view_token'], unique=True)
    op.create_table('requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('query', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('body_raw', sa.LargeBinary(), nullable=True),
    sa.Column('body_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body_size', sa.Integer(), nullable=False),
    sa.Column('body_truncated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requests_endpoint_id_id', 'requests', ['endpoint_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requests_endpoint_id_id', table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_endpoints_view_token'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_owner_user_id'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_ingest_token'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_expires_at'), table_name='endpoints')
    op.drop_table('endpoints')
    # ### end Alembic commands ###
