"""Capture endpoint management."""

from datetime import UTC, datetime, timedelta

from fastapi import APIRouter, status

from app.api.deps import EndpointDep, SessionDep, SettingsDep
from app.models import Endpoint
from app.schemas.endpoint import EndpointCreate, EndpointCreated, EndpointPublic

router = APIRouter(prefix="/api/endpoints", tags=["endpoints"])


def build_ingest_url(base: str, ingest_token: str) -> str:
    """Build the URL the user pastes into the provider's configuration."""
    return f"{base.rstrip('/')}/in/{ingest_token}"


@router.post("", response_model=EndpointCreated, status_code=status.HTTP_201_CREATED)
async def create_endpoint(
    data: EndpointCreate,
    session: SessionDep,
    settings: SettingsDep,
) -> EndpointCreated:
    """Create an anonymous capture endpoint.

    No sign-up required: that is what lets the tool be tried out in five seconds.
    In exchange, anonymous endpoints expire.
    """
    endpoint = Endpoint(
        name=data.name,
        expires_at=datetime.now(UTC) + timedelta(hours=settings.anon_retention_hours),
    )
    session.add(endpoint)
    await session.commit()
    # Values generated by the database -- created_at via its server default --
    # are not present on the Python object after an insert. Without this refresh
    # they would be None and the response would fail validation.
    await session.refresh(endpoint)

    return EndpointCreated(
        id=endpoint.id,
        name=endpoint.name,
        ingest_url=build_ingest_url(settings.public_ingest_base, endpoint.ingest_token),
        ingest_token=endpoint.ingest_token,
        view_token=endpoint.view_token,
        created_at=endpoint.created_at,
        expires_at=endpoint.expires_at,
    )


@router.get("/{view_token}", response_model=EndpointPublic)
async def get_endpoint(endpoint: EndpointDep, settings: SettingsDep) -> EndpointPublic:
    """Look up an endpoint by its read token.

    Access control is capability based: holding the token *is* the authorisation.
    The lookup and the 404 live in the `EndpointDep` dependency, so every route
    that reads through a view token gets the same check without repeating it.
    """
    return EndpointPublic(
        id=endpoint.id,
        name=endpoint.name,
        ingest_url=build_ingest_url(settings.public_ingest_base, endpoint.ingest_token),
        created_at=endpoint.created_at,
        expires_at=endpoint.expires_at,
        request_count=endpoint.request_count,
    )
