"""Capture endpoint management."""

from datetime import UTC, datetime, timedelta

from fastapi import APIRouter, HTTPException, status

from app.api.deps import EndpointDep, SessionDep, SettingsDep
from app.core.crypto import encrypt
from app.models import Endpoint
from app.schemas.endpoint import (
    EndpointCreate,
    EndpointCreated,
    EndpointPublic,
    SignatureConfigure,
)
from app.services.signatures import PROVIDERS

router = APIRouter(prefix="/api/endpoints", tags=["endpoints"])


def build_ingest_url(base: str, ingest_token: str) -> str:
    """Build the URL the user pastes into the provider's configuration."""
    return f"{base.rstrip('/')}/in/{ingest_token}"


@router.post("", response_model=EndpointCreated, status_code=status.HTTP_201_CREATED)
async def create_endpoint(
    data: EndpointCreate,
    session: SessionDep,
    settings: SettingsDep,
) -> EndpointCreated:
    """Create an anonymous capture endpoint.

    No sign-up required: that is what lets the tool be tried out in five seconds.
    In exchange, anonymous endpoints expire.
    """
    endpoint = Endpoint(
        name=data.name,
        expires_at=datetime.now(UTC) + timedelta(hours=settings.anon_retention_hours),
    )
    session.add(endpoint)
    await session.commit()
    # Values generated by the database -- created_at via its server default --
    # are not present on the Python object after an insert. Without this refresh
    # they would be None and the response would fail validation.
    await session.refresh(endpoint)

    return EndpointCreated(
        id=endpoint.id,
        name=endpoint.name,
        ingest_url=build_ingest_url(settings.public_ingest_base, endpoint.ingest_token),
        ingest_token=endpoint.ingest_token,
        view_token=endpoint.view_token,
        created_at=endpoint.created_at,
        expires_at=endpoint.expires_at,
    )


@router.get("/{view_token}", response_model=EndpointPublic)
async def get_endpoint(endpoint: EndpointDep, settings: SettingsDep) -> EndpointPublic:
    """Look up an endpoint by its read token.

    Access control is capability based: holding the token *is* the authorisation.
    The lookup and the 404 live in the `EndpointDep` dependency, so every route
    that reads through a view token gets the same check without repeating it.
    """
    return EndpointPublic(
        id=endpoint.id,
        name=endpoint.name,
        ingest_url=build_ingest_url(settings.public_ingest_base, endpoint.ingest_token),
        created_at=endpoint.created_at,
        expires_at=endpoint.expires_at,
        request_count=endpoint.request_count,
        signature_provider=endpoint.signature_provider,
    )


@router.put("/{view_token}/signature", response_model=EndpointPublic)
async def configure_signature(
    data: SignatureConfigure,
    endpoint: EndpointDep,
    session: SessionDep,
    settings: SettingsDep,
) -> EndpointPublic:
    """Start verifying signatures on this endpoint.

    Behind the *view* token, not the ingest one. The ingest token is public and
    ends up in configuration panels and logs; if it could set the signing secret,
    anyone who saw the URL could turn verification off or point it at a secret of
    their own.

    The secret is encrypted before it touches the database and is never returned
    by any route, so setting it again is the only way to change it.
    """
    if data.provider not in PROVIDERS:
        raise HTTPException(
            # ..._ENTITY is deprecated in current Starlette; same 422, current name.
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=f"Unknown provider '{data.provider}'. Supported: {', '.join(PROVIDERS)}.",
        )

    endpoint.signature_provider = data.provider
    endpoint.signature_secret = encrypt(data.secret)
    session.add(endpoint)
    await session.commit()

    return EndpointPublic(
        id=endpoint.id,
        name=endpoint.name,
        ingest_url=build_ingest_url(settings.public_ingest_base, endpoint.ingest_token),
        created_at=endpoint.created_at,
        expires_at=endpoint.expires_at,
        request_count=endpoint.request_count,
        signature_provider=endpoint.signature_provider,
    )


@router.delete("/{view_token}/signature", status_code=status.HTTP_204_NO_CONTENT)
async def clear_signature(endpoint: EndpointDep, session: SessionDep) -> None:
    """Stop verifying, and forget the stored secret.

    Both fields are cleared together: a provider with no secret would be a state
    that can only produce a useless verdict on every capture.
    """
    endpoint.signature_provider = None
    endpoint.signature_secret = None
    session.add(endpoint)
    await session.commit()
